# Generated by Django 3.1.4 on 2021-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210330_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
