# Generated by Django 3.1.13 on 2021-08-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210519_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersDemo',
            new_name='UserDemo',
        ),
    ]
